spring:
    datasource:
        ## MySQL Configuration
        url: jdbc:mysql://localhost:3307/employees
        username: admin
        password: 123456
    jpa:
        hibernate:
            ddl-auto: none
            use-new-id-generator-mappings: false
        properties:
            hibernate:
                # If it's used @Column(nullable = false) checks nullability before hit the DB.
                check_nullability: true
                # Logging and debugging (Set to false when finishing debug)
                show_sql: false
                use_sql_comments: false
                format_sql: true
## Security
security:
    oauth2:
        resource:
            jwk:
                key-set-uri: http://localhost:8081/auth/realms/springbootkeycloak/protocol/openid-connect/certs
## Custom Properties
global:
    client_id: employees-app
    client_secret: 7f6ced79-4875-43b5-811e-88817893b133
    grant_type: password
    scope: openid
    authentication_server_address: http://localhost:8081